
platform :ios, '9.0'
#use_frameworks!

target 'ReportingApps' do
    #---old
     pod 'RSKImageCropper'
     pod 'QBImagePickerController'
    #Before start, download added lib (get location) link: https://www.npmjs.com/package/react-native-get-location
    
    #--update for Crop Picker from: https://github.com/ivpusic/react-native-image-crop-picker
    # this is very important to have!
    # rn_path = '../node_modules/react-native'
    # pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    # pod 'React', path: rn_path, subspecs: [
    # 'Core',
    # 'RCTActionSheet',
    # 'RCTAnimation',
    # 'RCTGeolocation',
    # 'RCTImage',
    # 'RCTLinkingIOS',
    # 'RCTNetwork',
    # 'RCTSettings',
    # 'RCTText',
    # 'RCTVibration',
    # 'RCTWebSocket'
    # ]
    # pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
    # pod 'react-native-maps', :path => '../node_modules/react-native-maps'


  #latest from source: https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react native image crop picker
  # pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
